services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sql
      # Ref to https://stackoverflow.com/questions/50456780/run-mysql-on-port-3307-using-docker-compose
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  golang_lets_go:
    image: golang:latest
    volumes:
      - ../.:/go/src/app
    working_dir: /go/src/app
    # command: tail -f /dev/null
    command: go run ./cmd/web/
    ports:
      - 4000:4000
    depends_on:
      - db
